[package]
name = "bta30ctl"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
btleplug = { version = "0.11.5", features = ["serde"] }
futures-util = "0.3.30"
lazy_static = "1.4.0"

[dependencies.uuid]
version = "1.8.0"
